services:
  - type: web
    name: streamlit-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run main.py"
    envVars:
      - key: GEMINI_API_KEY
        value: "AIzaSyAG2adutwRWSSzS7RPiH1SrdmPbwLgMJKg"
